angular.module('myApplication.templates', []).run(['$templateCache', function($templateCache) {
  $templateCache.put("scripts/modules/core/views/footer.view.html",
    "<footer><div class=\"panel-footer text-center\"><p>This is the footer</p></div></footer>");
  $templateCache.put("scripts/modules/core/views/header.view.html",
    "<div data-ng-controller=HeaderController><div class=\"navbar transparent navbar-inverse navbar-fixed-top\" role=navigation><div class=container-fluid><div class=navbar-header><button type=button class=navbar-toggle data-toggle=collapse data-target=.navbar-collapse><span class=sr-only>Toggle navigation</span> <span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button> <a href=\"/#!/\" class=navbar-brand>Bob Peterson Photographer</a></div><div class=\"collapse navbar-collapse\"><ul class=\"nav navbar-nav\"><li ui-sref-active=active><a ui-sref=home>Home</a></li><li ui-sref-active=active><a ui-sref=about>About</a></li><div id=categories ng-hide=doHideCategories><div class=visible-xs><br><li style=margin-left:18px ng-repeat=\"item in headerModel.categoryies.category\"><a data-ng-click=selectACategory($index)>{{item.categoryName}}</a></li><br></div></div></ul></div></div></div></div>");
  $templateCache.put("scripts/modules/core/views/home.view.html",
    "<section data-ng-controller=HomeController id=home><div class=container><div class=row><div class=\"col-sm-3 col-md-2 sidebar\"><div class=logo><h1>Bob Peterson</h1><p>PHOTOGRAPHER</p></div><div class=row>&nbsp;</div><ul class=\"nav nav-sidebar\"><div ng-repeat=\"item in homeModel.categoryies.category\"><li><a data-ng-click=selectACategory($index) ng-class=\"{active: $index=== homeModel.curCatNum}\">{{item.categoryName}}</a></li></div><div class=contact><a href=mailto:bobpet@comcast.net><small>Contact Bob Peterson</small></a><br><small class=agent>Represented by Frank Meo<br>212.643.7428</small></div></ul></div><div class=\"rightside col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2\"><div class=mainImageHolder><a data-ng-click=getNextImage()><img id=img1 data-vertcenter data-img-error data-ng-src=//bobpeterson.com/photographer/{{homeModel.selectedImage}} class=\"center-block photo imageBig img-responsive animation-fade\" data-hereoimageloaded=animation-faded></a></div><div class=spinner></div><a class=\"left carousel-control\" role=button data-ng-click=getPrevImage()><span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=true></span> <span class=sr-only>Previous</span></a> <a class=\"right carousel-control\" role=button data-ng-click=getNextImage()><span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=true></span> <span class=sr-only>Next</span></a><div data-thumbscroller id=my-thumbs-list class=\"mThumbnailScroller center-block\"><ul class=\"center-block list-unstyled\"><li ng-repeat=\"item in homeModel.images\" class=pull-left><a data-ng-click=selectImage($index)><img img-error data-ng-src=//bobpeterson.com/photographer/{{item.imagethumb}} class=\"animation-fade photo center-block\" data-imageloaded=animation-faded></a></li></ul></div></div></div></div></section>");
  $templateCache.put("scripts/modules/about/views/about.view.html",
    "<section data-ng-controller=AboutController><div id=about class=container><div class=blog-header><h1 class=blog-title>Bob Peterson Photographer</h1><p class=\"lead blog-description\">He was a big man, but he moved like a cat.</p></div><div class=row><div class=\"col-sm-8 blog-main\"><div class=blog-post><div class=paragraphs><img class=img-responsive style=width:200px src=\"http://3.bp.blogspot.com/-7NGLsNrpnLo/UEobyKZAKWI/AAAAAAAABkQ/Ok3pP-dWO6g/s1600/Bob+Peterson.jpg\"></div><br><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p><hr><p>Cum sociis natoque penatibus et magnis <a href=#>dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p><p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p><h2>Heading</h2><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p></div></div></div></div></section>");
}]);
